config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'devise', controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "pages#dashboard"

    resources :users
    resources :books
    resources :legislations
  end

  resources :appointments
  
  root to: "pages#index"

  get "/articles" => "books#articles", as: :articles_path
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name, :city, :state, :segment, :role, :required => true, :on => :update
  mount_uploader :avatar, UserAvatarUploader
  self.per_page = 10

  before_create :add_user_role
  before_save :validate_user_fields

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc'  },
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )

  scope :search_query, lambda { |query|
    where("name LIKE ? OR email LIKE ? OR segment LIKE? OR city LIKE? OR state LIKE?", "%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%")
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^name/
      order("LOWER(users.name) #{ direction  }")
    when /^segment/
      order("LOWER(users.segment) #{ direction  }")
    when /^created_at/
      order("LOWER(users.created_at) #{ direction  }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect  }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc'],
      ['Área de atuação (a-z)', 'segment_asc'],
      ['Data de Registro (novos primeiro)', 'created_at_desc'],
      ['Data de Registro (antigos primeiro)', 'created_at_asc']
    ]
  end

  def add_user_role
    self.role = "user" if not self.role.present?
  end

  def validate_user_fields
    self.status = "active" if self.name.present?
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  layout 'devise'

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :segment, :city, :state, :avatar, :description])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  layout 'devise'

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :validate_profile_fields, except: [:edit, :update]
  before_action :restrict_actions, only: [:new, :create, :index, :destroy]

  # GET /users
  # GET /users.json
  def index
    @filterrific = initialize_filterrific(
      User,
      params[:filterrific],
      select_options: {
        sorted_by: User.options_for_sorted_by
      }
    ) or return
    @users = @filterrific.find.page(params[:page]).where(:status => "active")

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    redirect_to '/' if not current_user.role == 'Boss' || current_user == @user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if (@user.update_without_password(user_params) and current_user.role == 'Boss') or (@user.update(user_params))
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :segment, :city, :state, :avatar, :description, :email, :password, :password_confirmation, :status)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for(@user, defaults: { label: false, input_html: { class: "form-input" }}) do |f|
  - if f.error_notification
    %h2.subtitle= f.error_notification
    %br

  = f.input :name, placeholder: "Nome"
  = f.input :segment, placeholder: "Área de atuação"
  = f.input :city, placeholder: "Cidade"
  = f.input :state, placeholder: "Estado"
  = f.input :description, placeholder: "Fale um pouco sobre você...", input_html: { class: "form-input form-input--text" }

  - if current_user.role == "Boss"
    = f.input :email, placeholder: "Email"
    = f.input :password, placeholder: "Nova Senha"
    = f.input :password_confirmation, placeholder: "Confirmar Senha"

  - else
    %h4 Para fazer alterações, precisamos da sua senha
    = f.input :password, placeholder: "Senha"
    = link_to "Alterar meu email/senha", edit_user_registration_path, class: 'fancy-link fancy-link--purple'

  %br

  %br

  Foto de Perfil
  = f.input :avatar

  = f.submit "Salvar", class: "button button--green"

app/views/users/_list.html.haml
.landscape.landscape--white
  %br
  %h3 Vire a tela do celular
  = icon('fas', 'mobile')

#filterrific_results
  %br
  .table
    %table
      %thead
        %tr
          %th Name
          %th Segment
          %th City
          %th State
          %th{:colspan => "3"}
      %tbody
        - users.each do |user|
          %tr
            %td= user.name
            %td= user.segment
            %td= user.city
            %td= user.state
            %td= link_to icon('fas', 'eye', class: 'fancy-link--purple'), user
            %td= link_to icon('fas', 'edit', class: 'fancy-link--blue'), edit_user_path(user)
            %td= link_to icon('fas', 'trash', class: 'fancy-link--red'), user, method: :delete, data: { confirm: 'Are you sure?' }
    = will_paginate users # provided by will_paginate

app/views/users/edit.html.haml
.content.content--grey
  .content__inner
    - if flash.any?
      - flash.each do |flash|
        %p#flash{class: "#{flash[0]}"}= flash[1]
    %h1.title.title--purple Editar Perfil
    %br
    = render 'form', user: @user

app/views/users/index.html.haml
.content.content--purple
  .content__inner
    .card--centralized.card--text-center
      -if notice.present?
        %p#notice= notice

      %h1.title.title--white Usuários

      %br

      = form_for_filterrific @filterrific do |f|
        %div.inline
          = f.text_field(                              |
            :search_query,                             |
            class: 'filterrific-periodically-observed form-input', |
            placeholder: 'Buscar por algo...'             |
          )                                            |

        %div.inline
          = f.select(:sorted_by, @filterrific.select_options[:sorted_by])

        %div.inline{style: "margin-bottom: 15px"}
          = link_to reset_filterrific_url, class: "fancy-link" do
            %button.button Apagar Filtros

        %div.inline
          = f.submit "search", class: "button button--green"

      = render(                    |
        partial: 'users/list',     |
        locals: { users: @users  } |
      )                            |


      %br/
      = link_to icon('fas', 'user-plus', 'Novo usuário', class: 'fancy-link fancy-link--white'), new_user_path, class: 'fancy-link fancy-link--white'

app/views/users/index.js.haml
- js = escape_javascript(
- render(partial: 'users/list', locals: { users: @users  })
- )
$("#filterrific_results").html("#{js}");

app/views/users/new.html.haml
.content.content--grey.content--centralized
  .content__inner
    %h2.title.title--purple Novo
    %br
    = render 'form', user: @user

app/views/users/show.html.haml
.content.content--grey
  .content__inner
    .card--centralized.card--text-center
      - if notice.present?
        %p#notice= notice
      .profile-picture
        %img.profile-picture__img{src: "#{@user.avatar.url(:profile)}"}
      %h1.title.title--purple= @user.name
      %h1.subtitle= @user.segment
      %h3= @user.city + " | " + @user.state

      %p=@user.description

      - if current_user == @user
        .content__action
          = link_to edit_user_path(@user), class: "fancy-link fancy-link--purple" do
            = icon('fas', 'user-edit', " Editar meu perfil")

      %small.copyright
        © Gilcorp 2018. All right reserved | Made by
        %a{href: "https://rannyeribaptist.github.io"}rannyeribaptist.github.io