config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'devise', controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "pages#dashboard"

    resources :users
    resources :books
    resources :legislations
  end

  resources :appointments
  
  root to: "pages#index"

  get "/articles" => "books#articles", as: :articles_path
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :legislation

  mount_uploader :book, FilesUploader

  validates_presence_of :author, :legislation, :name, :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :restrict_actions, except: [:show]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, flash: {:success => 'Book was successfully created.'} }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { redirect_to books_path, flash: {:danger => 'Error, please verify your form and try again.'} }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, flash: {:success => 'Book was successfully updated.'} }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { redirect_to books_path, flash: {:danger => 'Error, please verify your form and try again.'} }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, flash: {:success => 'Book was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  def articles
  end

  # This action avoid common users to have access to important actions in this controller
  def restrict_actions
    redirect_to "/articles" if current_user.role == "user"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author, :legislation_id, :name, :book)
    end
end

app/views/books/_form.html.haml
= simple_form_for(book, defaults: { input_html: { class: 'form-input' } }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :author
  = f.association :legislation
  = f.input :name
  = f.input :book

  = f.submit "Salvar", class: "button button--green button--full-width"

app/views/books/_legislation-form.html.haml
= simple_form_for(Legislation.new, defaults: { input_html: { class: 'form-input' } }) do |f|
  = f.error_notification
  = f.input :name

  = f.submit "Salvar", class: "button button--green button--full-width"

app/views/books/_menu.html.haml
- content_for :menu do
  .sidebar__content
    .dropdown
      .dropdown__content.toggle{"data-toggle" => "drop-menu-1", "data-filter" => false}
        %h3.title.title--dark-grey.title--small + Livro
      .dropdown__drop#drop-menu-1
        %br
        = render 'form', book: Book.new

    .dropdown
      .dropdown__content.toggle{"data-toggle" => "drop-menu-2", "data-filter" => false}
        %h3.title.title--dark-grey.title--small.title--nowrap + Legislação
      .dropdown__drop#drop-menu-2
        %br
        = render 'legislation-form'

  .sidebar__mobile
    = icon('fas', 'bars', class: 'icon icon--black toggle', "data-toggle" => "mobile-menu")
    .sidebar__mobile-show#mobile-menu
      %a{:href => "#", class: 'fancy-link fancy-link--dark-grey fancy-link--with-icon fancy-link--large toggle', "data-toggle" => "modal_form", "data-filter" => "true", "data-turbolinks" => "false"}
        = icon('fas', 'plus', 'Novo Livro')

- content_for :javascript do
  :javascript
    $(document).ready(function() {
      $('.toggle').click(function() {
        let id = $(this).attr("data-toggle");
        let filter = $(this).attr("data-filter")

        console.log(filter);

        if (filter) {
          if ($('.site-content').hasClass('filter')) {
          $('.site-content').removeClass('filter');
          } else {
          $('.site-content').addClass('filter');
          }
        }

        $('#' + id).toggle()
      });
    });

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
= render 'menu'

.content.content--grey
  .content__inner.content__inner--full-width

    - if flash.any?
      - flash.each do |f|
        %p#flash{class: "#{f[0]}"}= f[1]

    %h1.title.title--purple Livros

    - @books.each_slice(4) do |books|
      .columns
        - books.each do |book|
          .column.column--4
            .card.card--white.card--bordered
              .card__content
                %div{id: "show_#{book.id}"}
                  %h1.subtitle= book.author

                  %br
                  %em= book.name
                  %br

                  %strong= book.legislation.name
                  %a{:href => "#{book.book.url}", target: "_blank"}
                  %br
                  %br
                %div{style: "display:none", id: "form_#{book.id}"}
                  = render 'form', book: book

                %hr
                .advanced-inline
                  %a{:href => "#{book.book.url}", target: "_blank", class: 'fancy-link fancy-link--with-icon fancy-link--purple'}= icon('fas', 'external-link-square-alt', 'Ver')
                  %a{:href => "#", class: 'fancy-link fancy-link--with-icon fancy-link--blue edit', "data-id" => "#{book.id}", "data-turbolinks" => "false"}= icon('fas', 'pen', 'Editar')
                  = link_to book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fancy-link fancy-link--with-icon fancy-link--red' do
                    = icon('fas', 'trash', 'Excluir')

- content_for :modal do
  .modal#modal_form
    .modal__content
      = icon('fas', 'times', class: 'icon icon--close toggle', "data-toggle" => "modal_form", "data-filter" => true)

      %h1.title.title--purple Novo Livro
      %br
      = render 'form', book: Book.new
      %h1.title.title--purple Nova Legislação
      %br
      = render 'legislation-form'

- content_for :javascript do
  :javascript
    $(document).ready(function() {
      $('.edit').click(function() {
        let id = $(this).attr("data-id");
        $('#show_' + id).toggle()
        $('#form_' + id).toggle()
      });
    });

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Back', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Author:
  = @book.author
%p
  %b Legislation:
  = @book.legislation
%p
  %b Name:
  = @book.name
%p
  %b Book:
  = @book.book

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path