config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'devise', controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  authenticated :user do
    root to: "pages#dashboard"

    resources :users
    resources :books
    resources :legislations
  end

  resources :appointments
  
  root to: "pages#index"

  get "/articles" => "books#articles", as: :articles_path
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates_presence_of :name, :email, :phone, :demand, :preference
  self.per_page = 10

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc'  },
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )

  scope :search_query, lambda { |query|
    where("name LIKE ? OR email LIKE ? OR demand LIKE? OR phone LIKE? OR preference LIKE?", "%#{query}%","%#{query}%","%#{query}%","%#{query}%","%#{query}%")
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^name/
      order("LOWER(appointments.name) #{ direction }")
    when /^preference/
      order("LOWER(appointments.preference) #{ direction }")
    when /^created_at/
      order("LOWER(appointments.created_at) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect  }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc'],
      ['Forma de contato (a-z)', 'preference_asc'],
      ['Data de Registro (novos primeiro)', 'created_at_desc'],
      ['Data de Registro (antigos primeiro)', 'created_at_asc']
    ]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :restrict_actions, except: [:new, :create]

  layout "appointment", only: [:new, :create]

  # GET /appointments
  # GET /appointments.json
  def index
    @filterrific = initialize_filterrific(
      Appointment,
      params[:filterrific],
      select_options: {
        sorted_by: Appointment.options_for_sorted_by
      }
    ) or return
    @appointments = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to new_appointment_url, flash: {success: "Tudo pronto #{@appointment.name}. Entraremos em contato com você por #{@appointment.preference} o quanto antes."} }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, flash: {notice: 'Appointment was successfully updated.'} }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, flash: {danger: 'Appointment was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :email, :phone, :demand, :preference)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.haml
= simple_form_for(@appointment, defaults: { input_html: { class: 'form-input' } }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .card.card--white{style: "text-align: left"}
    .card__content
      .form-inputs
        = f.input :name
        = f.input :email, as: :email
        = f.input :phone, class: "phone"
        = f.input :demand, as: :text
        = f.input :preference, as: :select, collection: ["Whatsapp", "Ligação Telefônica", "Email"], label: "Como você prefere que entremos em contato?"

  %br

  .advanced-inline
    = link_to 'Voltar', :back, class: 'fancy-link fancy-link--white'
    = f.submit "Solicitar atendimento", class: "button button--green"

app/views/appointments/_list.html.haml
.landscape.landscape--white
  %br
  %h3 Vire a tela do celular
  = icon('fas', 'mobile')

#filterrific_results
  %br
  .table
    %table
      %thead
        %tr
          %th Nome
          %th Email
          %th Telefone
          %th Preferência
          %th
          %th

      %tbody
        - appointments.each do |appointment|
          %tr
            %td= appointment.name
            %td= appointment.email
            %td= appointment.phone
            %td= appointment.preference
            %td= link_to icon('fas', 'eye', class: 'fancy-link fancy-link--purple'), appointment
            %td= link_to icon('fas', 'trash', class: 'fancy-link fancy-link--red'), appointment, method: :delete, data: { confirm: 'Are you sure?' }
    = will_paginate appointments # provided by will_paginate

app/views/appointments/edit.html.haml
%h1 Editing appointment

= render 'form'

= link_to 'Show', @appointment
\|
= link_to 'Back', appointments_path

app/views/appointments/index.html.haml
.content.content--purple
  .content__inner
    .card--centralized.card--text-center
      -if notice.present?
        %p#notice= notice

      %h1.title.title--white.title--thin.title--large Solicitações de Atendimento

      %br

      = form_for_filterrific @filterrific do |f|
        %div{style: "display: inline-block"}
          = f.text_field(                              |
            :search_query,                             |
            class: 'filterrific-periodically-observed form-input', |
            placeholder: 'Buscar por algo...'             |
          )                                            |

        %div{style: "display: inline-block"}
          = f.select(:sorted_by, @filterrific.select_options[:sorted_by])

        %div{style: "margin-bottom: 15px; display: inline-block"}
          = link_to reset_filterrific_url, class: "fancy-link" do
            %button.button Apagar Filtros

        %div{style: "display: inline-block"}
          = f.submit "search", class: "button button--green"

      = render(                    |
        partial: 'appointments/list',     |
        locals: { appointments: @appointments  } |
      )                            |

app/views/appointments/index.js.haml
- js = escape_javascript(
- render(partial: 'appointments/list', locals: { appointments: @appointments  })
- )
$("#filterrific_results").html("#{js}");

app/views/appointments/new.html.haml
%h1.title.title--white{style: "margin-bottom: 0"} Solicitar Atendimento
%h6.subtitle.subtitle--grey{style: "margin-top: 0"} Solicite atendimento e entraremos em contato com você

%br

- if flash.any?
  - flash.each do |flash|
    %p#flash{class: "#{flash[0]}"}= flash[1]

= notice


= render 'form'

app/views/appointments/show.html.haml
.content.content--grey
  - if notice
    %p#notice= notice

  .card.card--white
    .card__content
      %h1.title.title--thin= @appointment.name
      %p= "Email: " + @appointment.email
      %p= "Telefone: " + @appointment.phone
      %p= "Demanda: " + @appointment.demand
      %p= "Preferência: " + @appointment.preference
      %p= "Data da solicitação: " + @appointment.created_at.strftime("%d de %B")

      %hr

      .advanced-inline
        = link_to "Voltar", :back, class: "fancy-link fancy-link--purple"
        = link_to icon('fas', 'trash', 'Excluir', class: 'fancy-link fancy-link--red'), @appointment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fancy-link fancy-link--red'